<?php

namespace App\Constants;

return [
    //Home
    'SLIDER_IMAGE_MAX_SIZE'=>'2048',
    'SLIDER_IMAGE_MIN_SIZE'=>'180',

    'DISASTER_WEB_PORTAL_IMAGE_MAX_SIZE'=>'120',
    'DISASTER_WEB_PORTAL_IMAGE_MIN_SIZE'=>'40',

    'DISASTER_MANAGEMENT_NEWS_IMAGE_MAX_SIZE'=>'2048',
    'DISASTER_MANAGEMENT_NEWS_IMAGE_MIN_SIZE'=>'180',
    
    'WEBSITE_LOGO_MAX_SIZE'=>'600',
    'WEBSITE_LOGO_MIN_SIZE'=>'5',

    'DEPARTMENT_INFORMATION_IMAGE_MAX_SIZE'=>'22',
    'DEPARTMENT_INFORMATION_IMAGE_MIN_SIZE'=>'10',

    'DEPARTMENT_INFORMATION_NEW_IMAGE_MAX_SIZE'=>'300',
    'DEPARTMENT_INFORMATION_NEW_IMAGE_MIN_SIZE'=>'100',
    
    'DISASTER_MANAGEMENT_PORTAL_IMAGE_MAX_SIZE'=>'2048',
    'DISASTER_MANAGEMENT_PORTAL_IMAGE_MIN_SIZE'=>'180',

    'OBJECTIVE_GOALS_IMAGE_MAX_SIZE'=>'2048',
    'OBJECTIVE_GOALS_IMAGE_MIN_SIZE'=>'180',

    'DISASTER_MANAGEMENT_AUTHORITY_IMAGE_MAX_SIZE'=>'2048',
    'DISASTER_MANAGEMENT_AUTHORITY_IMAGE_MIN_SIZE'=>'180',

    'HAZARD_VULNERABILITY_IMAGE_MAX_SIZE'=>'2048',
    'HAZARD_VULNERABILITY_IMAGE_MIN_SIZE'=>'180',

    'CAPACITY_TRAINING_IMAGE_MAX_SIZE'=>'2048',
    'CAPACITY_TRAINING_IMAGE_MIN_SIZE'=>'180',

    'EARLY_WARNING_SYSTEM_IMAGE_MAX_SIZE'=>'2048',
    'EARLY_WARNING_SYSTEM_IMAGE_MIN_SIZE'=>'180',

    'PUBLIC_AWARENESS_EDUCATION_IMAGE_MAX_SIZE'=>'2048',
    'PUBLIC_AWARENESS_EDUCATION_IMAGE_MIN_SIZE'=>'180',

    'DISTRICT_EMERGENCY_OPERATION_CENTER_IMAGE_MAX_SIZE'=>'2048',
    'DISTRICT_EMERGENCY_OPERATION_CENTER_IMAGE_MIN_SIZE'=>'180',

    'EMERGENCY_CONTACT_NUMBER_IMAGE_MAX_SIZE'=>'2048',
    'EMERGENCY_CONTACT_NUMBER_IMAGE_MIN_SIZE'=>'180',

    'EVACUATION_PLAN_IMAGE_MAX_SIZE'=>'2048',
    'EVACUATION_PLAN_IMAGE_MIN_SIZE'=>'180',

    'RELIEF_MEASURES_RESOURCES_IMAGE_MAX_SIZE'=>'2048',
    'RELIEF_MEASURES_RESOURCES_IMAGE_MIN_SIZE'=>'180',

    'SEARCH_RESCUSE_TEAM_IMAGE_MAX_SIZE'=>'2048',
    'SEARCH_RESCUSE_TEAM_IMAGE_MIN_SIZE'=>'180',

    'STATE_EMERGENCY_OPERATIONS_CENTER_IMAGE_MAX_SIZE'=>'2048',
    'STATE_EMERGENCY_OPERATIONS_CENTER_IMAGE_MIN_SIZE'=>'180',

    'TRAINING_EVENT_IMAGE_MAX_SIZE'=>'2048',
    'TRAINING_EVENT_IMAGE_MIN_SIZE'=>'180',

    'HOME_TENDER_PDF_MAX_SIZE'=>'7168',
    'HOME_TENDER_PDF_MIN_SIZE'=>'150',

    'DISTRICT_DISASTER_MANAGEMENT_PLAN_PDF_MAX_SIZE'=>'7168',
    'DISTRICT_DISASTER_MANAGEMENT_PLAN_PDF_MIN_SIZE'=>'150',

    'STATE_DISASTER_MANAGEMENT_PLAN_PDF_MAX_SIZE'=>'7168',
    'STATE_DISASTER_MANAGEMENT_PLAN_PDF_MIN_SIZE'=>'150',

    'RELEVANT_LAWS_REGULATIONS_PDF_MAX_SIZE'=>'7168',
    'RELEVANT_LAWS_REGULATIONS_PDF_MIN_SIZE'=>'150',

    'STATE_DISASTER_MANAGEMENT_POLICY_PDF_MAX_SIZE'=>'7168',
    'STATE_DISASTER_MANAGEMENT_POLICY_PDF_MIN_SIZE'=>'150',

    'RTI_PDF_MAX_SIZE'=>'7168',
    'RTI_PDF_MIN_SIZE'=>'150',

    'VACANCY_PDF_MAX_SIZE'=>'7168',
    'VACANCY_PDF_MIN_SIZE'=>'150',

    'DOCUMENT_PUBLICATION_PDF_MAX_SIZE'=>'7168',
    'DOCUMENT_PUBLICATION_PDF_MIN_SIZE'=>'150',
];