<?php

namespace App\Constants;

return [
    //Home
    'SLIDER_IMAGE_MAX_SIZE'=>'2048',
    'SLIDER_IMAGE_MIN_SIZE'=>'180',

    'DISASTER_WEB_PORTAL_IMAGE_MAX_SIZE'=>'120',
    'DISASTER_WEB_PORTAL_IMAGE_MIN_SIZE'=>'40',

    'DISASTER_MANAGEMENT_NEWS_IMAGE_MAX_SIZE'=>'2048',
    'DISASTER_MANAGEMENT_NEWS_IMAGE_MIN_SIZE'=>'180',
    
    'WEBSITE_LOGO_MAX_SIZE'=>'11',
    'WEBSITE_LOGO_MIN_SIZE'=>'5',
    
	

];